import * as lancedb from '@lancedb/lancedb';
import { Field, Int64, Schema, Utf8 } from 'apache-arrow';

import { LocalMindError, describeUnknownError } from '../core/errors';
import { createLogger } from '../core/logger';

/**
 * Document persistence.
 *
 * Stage 1 stored only *chunks*, which is all retrieval needs. That is fine for a
 * read-only corpus on disk, and insufficient the moment a UI has to list, edit
 * and delete documents: chunks are lossy (overlap duplicates text, the
 * splitter drops nothing but reorders nothing either) so you cannot reliably
 * reconstruct an editable document from them.
 *
 * So documents get their own table, in the same LanceDB directory. No vector
 * column - this is a plain columnar table used for metadata queries and
 * round-tripping the editable source text.
 *
 * The `origin` column is what makes the Studio honest about provenance: a
 * document typed into the UI, one loaded from `corpus/`, and one generated by
 * the GitHub analyzer behave identically for retrieval but very differently when
 * you re-run a sync, and the UI needs to say which is which.
 */

const log = createLogger('store:documents');

export const DOCUMENT_ORIGINS = ['manual', 'file', 'github', 'service', 'api'] as const;
export type DocumentOrigin = (typeof DOCUMENT_ORIGINS)[number];

export interface CorpusDocument {
  readonly id: string;
  readonly title: string;
  /** Citation-facing identifier: a path, URL, or `table/pk`. */
  readonly sourcePath: string;
  readonly origin: DocumentOrigin;
  readonly text: string;
  readonly contentHash: string;
  /** Free-form labels, used by the Studio for filtering. */
  readonly tags: readonly string[];
  /** Which source run produced this, e.g. `github:vercel/ai@main`. Empty for manual. */
  readonly sourceRef: string;
  readonly chunkCount: number;
  readonly createdAt: string;
  readonly updatedAt: string;
}

const COLUMNS = [
  'id',
  'title',
  'sourcePath',
  'origin',
  'text',
  'contentHash',
  'tags',
  'sourceRef',
  'chunkCount',
  'createdAt',
  'updatedAt',
] as const;

export function buildDocumentSchema(): Schema {
  return new Schema([
    new Field('id', new Utf8(), false),
    new Field('title', new Utf8(), false),
    new Field('sourcePath', new Utf8(), false),
    new Field('origin', new Utf8(), false),
    new Field('text', new Utf8(), false),
    new Field('contentHash', new Utf8(), false),
    // Arrow has a List type, but a JSON string keeps the schema flat and the SQL
    // predicates simple (`tags LIKE '%"api"%'`). Tag counts here are single
    // digits; this is not a case where a nested type earns its complexity.
    new Field('tags', new Utf8(), false),
    new Field('sourceRef', new Utf8(), false),
    new Field('chunkCount', new Int64(), false),
    new Field('createdAt', new Utf8(), false),
    new Field('updatedAt', new Utf8(), false),
  ]);
}

function readString(row: Record<string, unknown>, key: string): string {
  const value = row[key];
  if (typeof value === 'string') return value;
  if (value === null || value === undefined) return '';
  return String(value);
}

function readNumber(row: Record<string, unknown>, key: string): number {
  const value = row[key];
  if (typeof value === 'number') return value;
  if (typeof value === 'bigint') return Number(value);
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function parseTags(raw: string): string[] {
  if (raw.length === 0) return [];
  try {
    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((tag): tag is string => typeof tag === 'string') : [];
  } catch {
    return [];
  }
}

function parseOrigin(raw: string): DocumentOrigin {
  return (DOCUMENT_ORIGINS as readonly string[]).includes(raw) ? (raw as DocumentOrigin) : 'manual';
}

function toDocument(row: Record<string, unknown>): CorpusDocument {
  return {
    id: readString(row, 'id'),
    title: readString(row, 'title'),
    sourcePath: readString(row, 'sourcePath'),
    origin: parseOrigin(readString(row, 'origin')),
    text: readString(row, 'text'),
    contentHash: readString(row, 'contentHash'),
    tags: parseTags(readString(row, 'tags')),
    sourceRef: readString(row, 'sourceRef'),
    chunkCount: readNumber(row, 'chunkCount'),
    createdAt: readString(row, 'createdAt'),
    updatedAt: readString(row, 'updatedAt'),
  };
}

function sqlString(value: string): string {
  return `'${value.replace(/'/gu, "''")}'`;
}

export interface DocumentQuery {
  readonly origin?: DocumentOrigin;
  readonly sourceRef?: string;
  /** Case-insensitive substring match over title and sourcePath. */
  readonly search?: string;
  readonly limit?: number;
  readonly offset?: number;
}

export interface DocumentStore {
  list(query?: DocumentQuery): Promise<readonly CorpusDocument[]>;
  get(id: string): Promise<CorpusDocument | undefined>;
  /** Insert or replace by id. */
  put(document: CorpusDocument): Promise<void>;
  putMany(documents: readonly CorpusDocument[]): Promise<number>;
  remove(id: string): Promise<boolean>;
  /** Delete every document from one source run. Returns the ids removed. */
  removeBySourceRef(sourceRef: string): Promise<readonly string[]>;
  count(): Promise<number>;
  close(): Promise<void>;
}

export interface OpenDocumentStoreOptions {
  readonly dbPath: string;
  readonly tableName?: string;
}

export async function openDocumentStore(options: OpenDocumentStoreOptions): Promise<DocumentStore> {
  const tableName = options.tableName ?? 'documents';

  let connection: lancedb.Connection;
  let table: lancedb.Table;

  try {
    connection = await lancedb.connect(options.dbPath);
    const names = await connection.tableNames();
    table = names.includes(tableName)
      ? await connection.openTable(tableName)
      : await connection.createEmptyTable(tableName, buildDocumentSchema(), { mode: 'overwrite' });
  } catch (error) {
    throw new LocalMindError('VECTOR_STORE_FAILED', `Could not open the document table: ${describeUnknownError(error)}`, {
      remedy: 'Check that LOCALMIND_DB_PATH is writable and not held open by another process.',
      details: { dbPath: options.dbPath, tableName },
      cause: error,
    });
  }

  /** See the same helper in vector-store.ts for why this exists. */
  async function withRefresh<T>(label: string, operation: () => Promise<T>): Promise<T> {
    try {
      return await operation();
    } catch (error) {
      const message = describeUnknownError(error);
      if (!/Not found:.*\.lance|dataset (?:version|not found)|commit conflict/iu.test(message)) throw error;
      log.warn('document table changed underneath this handle; checking out latest', { label });
      await table.checkoutLatest();
      return operation();
    }
  }

  async function rows(where?: string, limit = 10_000): Promise<Record<string, unknown>[]> {
    return withRefresh('query', async () => {
      let query = table.query().select([...COLUMNS]).limit(limit);
      if (where !== undefined && where.length > 0) query = query.where(where);
      return (await query.toArray()) as Record<string, unknown>[];
    });
  }

  async function putMany(documents: readonly CorpusDocument[]): Promise<number> {
    if (documents.length === 0) return 0;
    try {
      await withRefresh('putMany', () =>
        table
        .mergeInsert('id')
        .whenMatchedUpdateAll()
        .whenNotMatchedInsertAll()
        .execute(
          documents.map((document) => ({
            id: document.id,
            title: document.title,
            sourcePath: document.sourcePath,
            origin: document.origin,
            text: document.text,
            contentHash: document.contentHash,
            tags: JSON.stringify(document.tags),
            sourceRef: document.sourceRef,
            chunkCount: document.chunkCount,
            createdAt: document.createdAt,
            updatedAt: document.updatedAt,
          })) as unknown as Record<string, unknown>[],
        ),
      );
      log.debug('documents upserted', { count: documents.length });
      return documents.length;
    } catch (error) {
      throw new LocalMindError('VECTOR_STORE_FAILED', `Saving documents failed: ${describeUnknownError(error)}`, {
        remedy: 'Retry with fewer documents; if it persists, rebuild the index.',
        details: { count: documents.length },
        cause: error,
      });
    }
  }

  return {
    async list(query = {}): Promise<readonly CorpusDocument[]> {
      const predicates: string[] = [];
      if (query.origin !== undefined) predicates.push(`origin = ${sqlString(query.origin)}`);
      if (query.sourceRef !== undefined) predicates.push(`sourceRef = ${sqlString(query.sourceRef)}`);

      try {
        const found = await rows(predicates.join(' AND '));
        let documents = found.map(toDocument);

        // Substring search is applied in application code rather than SQL: it has
        // to be case-insensitive across two columns, and LanceDB predicates do
        // not offer a portable ILIKE.
        if (query.search !== undefined && query.search.trim().length > 0) {
          const needle = query.search.trim().toLowerCase();
          documents = documents.filter(
            (document) =>
              document.title.toLowerCase().includes(needle) ||
              document.sourcePath.toLowerCase().includes(needle) ||
              document.tags.some((tag) => tag.toLowerCase().includes(needle)),
          );
        }

        documents.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));

        const offset = Math.max(0, query.offset ?? 0);
        const limit = query.limit ?? documents.length;
        return documents.slice(offset, offset + limit);
      } catch (error) {
        throw new LocalMindError('VECTOR_STORE_FAILED', `Listing documents failed: ${describeUnknownError(error)}`, {
          remedy: 'Rebuild the index if the table is corrupt.',
          cause: error,
        });
      }
    },

    async get(id): Promise<CorpusDocument | undefined> {
      const found = await rows(`id = ${sqlString(id)}`, 1);
      const first = found[0];
      return first === undefined ? undefined : toDocument(first);
    },

    put: async (document): Promise<void> => {
      await putMany([document]);
    },

    putMany,

    async remove(id): Promise<boolean> {
      const before = await table.countRows();
      await table.delete(`id = ${sqlString(id)}`);
      return (await table.countRows()) < before;
    },

    async removeBySourceRef(sourceRef): Promise<readonly string[]> {
      const found = await rows(`sourceRef = ${sqlString(sourceRef)}`);
      const ids = found.map((row) => readString(row, 'id'));
      if (ids.length > 0) {
        await table.delete(`sourceRef = ${sqlString(sourceRef)}`);
        log.info('documents removed by source ref', { sourceRef, count: ids.length });
      }
      return ids;
    },

    count: () => withRefresh('count', () => table.countRows()),

    close(): Promise<void> {
      table.close();
      connection.close();
      return Promise.resolve();
    },
  };
}
